//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article()
        {
            this.Comments = new HashSet<Comment>();
            this.likes = new HashSet<like>();
            this.statistics = new HashSet<statistic>();
        }
    
        public int article_id { get; set; }
        public int category_id { get; set; }
        public string article_name { get; set; }
        public string description { get; set; }
        public string article_name_en { get; set; }
        public string description_en { get; set; }
        public string thumbnail { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string tags { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> ghim { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<statistic> statistics { get; set; }
        public virtual User User { get; set; }
    }
}
