//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewspaperEntities : DbContext
    {
        public NewspaperEntities()
            : base("name=NewspaperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<cms_contact> cms_contact { get; set; }
        public virtual DbSet<cms_mail> cms_mail { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<follow> follows { get; set; }
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<statistic> statistics { get; set; }
        public virtual DbSet<thongbao> thongbaos { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<block> blocks { get; set; }
    }
}
