//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.articles = new HashSet<article>();
            this.blogs = new HashSet<blog>();
            this.cms_mail = new HashSet<cms_mail>();
            this.Comments = new HashSet<Comment>();
            this.follows = new HashSet<follow>();
            this.likes = new HashSet<like>();
            this.thongbaos = new HashSet<thongbao>();
            this.blocks = new HashSet<block>();
        }
    
        public int user_id { get; set; }
        [Required(ErrorMessage ="Please, enter the username")]
        [RegularExpression("^([a-zA-Z0-9]+)$",ErrorMessage ="Username is not contains special characters!")]
        [StringLength(16,MinimumLength =6,ErrorMessage ="The length of user must be from 6 to 16 characters")]
        public string username { get; set; }
        [Required(ErrorMessage ="Please, enter the password")]
        public string password { get; set; }
        [Required(ErrorMessage ="Please, enter the email")]
        public string email { get; set; }
        public string fullname { get; set; }
        public string nickname { get; set; }
        public string gender { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> birthday { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string favourite { get; set; }
        public Nullable<int> post { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> timeJoin { get; set; }
        public string avatar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article> articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog> blogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cms_mail> cms_mail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<follow> follows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thongbao> thongbaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<block> blocks { get; set; }
    }
}
